Repository MotuS-Web/MotuS-FrontEnd, pull requests merged in 2023-08, with the labels that each got.

#9 [Feat/FE] 사용자의 조건에 따라 필터링되는 운동 카드 컴포넌트 기능을 구현한다.
  .github/ISSUE_TEMPLATE/✅-feature.md
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend

#10 [Feat/FE] 더미데이터를 생성해 exercise-api.js로 저장한다.
  .github/PULL_REQUEST_TEMPLATE.md
  src/assets/images/course-placeholder.jpg
  src/librarys/exercise-api.js
  src/pages/MainPage.jsx
Labels: 💻 frontend, 📈 test

#11 [Feat/FE] 운동상세수강페이지를 구현한다.
  src/App.jsx
  src/assets/images/Check-After.png
  src/assets/images/Check-Before.png
  src/components/CourseCard.jsx
  src/pages/CourseDetail.jsx
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend, 📱 ui

#19 [Feat/FE] modal 컴포넌트 추가
  package-lock.json
  package.json
  src/components/Modal.jsx
  src/components/player/StartupModal.jsx
  src/librarys/context.js
  src/reducer/modal.js
  vercel.json
Labels: 🔨 feature, 💻 frontend, 📱 ui

#20 Feat: 수강 진행 페이지의 와이어프레임을 구현한다.
  package-lock.json
  package.json
  src/App.jsx
  src/assets/videos/sample_video.mp4
  src/components/player/ControllerSection.jsx
  src/components/player/GuideSection.jsx
  src/components/player/StartupModal.jsx
  src/components/player/Subtitle.jsx
  src/index.scss
  src/pages/PlayerPage.jsx
Labels: 🔨 feature, 💻 frontend, 🎨 design

#21 [Feat/FE] Player 매니저 구현 및 웹캠 및 웹캠 녹화 기능 연결한다.
  src/components/player/ControllerSection.jsx
  src/components/player/GuideSection.jsx
  src/components/player/StartupModal.jsx
  src/librarys/player.js
  src/pages/PlayerPage.jsx
  src/reducer/player.js
Labels: 🔨 feature, 💻 frontend

#22 [Feat/FE] 로그인 모달 구현 / login 로그인 계정(관리자/유저) 더미 데이터를 생성 후 메인 페이지 적용
  package-lock.json
  package.json
  src/App.jsx
  src/components/Header.jsx
  src/components/Modal.jsx
  src/components/player/StartupModal.jsx
  src/librarys/context.js
  src/librarys/context.jsx
  src/librarys/login-api.js
  src/pages/PlayerPage.jsx
  src/redux/store.js
  src/redux/userSlice.js
Labels: 🔨 feature, 💻 frontend, 📈 test, 📱 ui

#23 [Feat/FE] 수강 내역의 시간 타입 변경 / 계정 유형에 따른 헤더 nav 권한 부여 구현
  src/components/CourseCard.jsx
  src/components/Header.jsx
  src/librarys/exercise-api.js
Labels: 🔨 feature, 💻 frontend, 📈 test

#24 [Feat/FE] 카테고리를 기준으로 수강 이미지 랜더링 구현 / login-api.js를 활용해 로그인 임시 연결 완료
  src/assets/images/arms-up.webp
  src/assets/images/knee.webp
  src/assets/images/shoulder-up.webp
  src/assets/images/thigh.webp
  src/components/CourseCard.jsx
  src/librarys/exercise-api.js
  src/pages/CourseDetail.jsx
  src/pages/MainPage.jsx
  src/pages/MyCourse.jsx
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend, 📈 test

#26 [Feat/FE] 프로그램 수강 화면에 API 및 State 연결한다.
  package-lock.json
  src/components/player/ControllerSection.jsx
  src/components/player/Countdown.jsx
  src/components/player/GuideSection.jsx
  src/components/player/Subtitle.jsx
  src/librarys/player.js
  src/pages/MainPage.jsx
  src/pages/PlayerPage.jsx
  src/reducer/player.js
Labels: 🔨 feature, 💻 frontend, 📱 ui

#29 !HOTFIX: courseList에서도 해당 ID의 코스를 찾을 수 있도록함
  package-lock.json
  package.json
  src/librarys/exercise-api.js
  src/pages/AddExercise.jsx
Labels: 🔥 hotfix

#30 [Feat/FE] modal을 redux로 수정 및 결과 modal 추가합니다.
  src/App.jsx
  src/components/Header.jsx
  src/components/LoginModal.jsx
  src/components/Modal.jsx
  src/components/player/ResultModal.jsx
  src/components/player/StartupModal.jsx
  src/librarys/player.js
  src/pages/PlayerPage.jsx
  src/redux/modalSlice.js
  src/redux/store.js
Labels: 🔨 feature, 💻 frontend, 📱 ui

#32 [Fix/FE] 백엔드 api 요청으로 인한 강의 컴포넌트 수정 및 더미데이터 구조 수정
  README.md
  src/components/CourseCard.jsx
  src/librarys/exercise-api.js
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
Labels: 🔧 fix_issue, 💻 frontend, 🛠️ refactoring
