Repository MotuS-Web/MotuS-FrontEnd, pull requests merged in 2023-09, with the labels that each got.

#33 [Feat/FE] 프로그램 등록, 비디오 등록, 프로그램 상세 정보 조회, 로그인 api 연동한다.
  package-lock.json
  src/components/Header.jsx
  src/components/LoginModal.jsx
  src/librarys/exercise-api.js
  src/librarys/login-api.js
  src/pages/AddExercise.jsx
  src/pages/CourseDetail.jsx
Labels: 🔨 feature, 💻 frontend

#35 [Feat/FE] 로그인 API 최종 연결한다.
  package-lock.json
  package.json
  src/App.jsx
  src/components/LoginModal.jsx
  src/components/SkeletonVideo.jsx
  src/librarys/axios.js
  src/librarys/login-api.js
  src/librarys/util.js
  src/pages/AddExercise.jsx
  src/redux/userSlice.js
Labels: 🔑 auth, 🔨 feature, 💻 frontend

#36 [Feat/FE] 프로그램 목록 조회 API 구현한다.
  src/components/LoginModal.jsx
  src/librarys/exercise-api.js
  src/librarys/type.js
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend

#37 [Feat/FE] 프로그램 상세페이지 API 연결을 진행합니다.
  src/App.jsx
  src/components/CourseCard.jsx
  src/components/LoginModal.jsx
  src/components/SkeletonVideo.jsx
  src/librarys/exercise-api.js
  src/librarys/player.js
  src/pages/CourseDetail.jsx
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend, 📈 test

#38 [Feat/FE] 수강 내역에 API를 연결한다.
  src/components/Header.jsx
  src/librarys/axios.js
  src/librarys/my-program-api.js
  src/pages/MyCourse.jsx
  src/redux/userSlice.js
Labels: 🔨 feature, 💻 frontend

#39 [Feat/FE] 치료 페이지 API 연결
  src/components/player/GuideSection.jsx
  src/components/player/ResultModal.jsx
  src/librarys/axios.js
  src/librarys/exercise-api.js
  src/librarys/player.js
  src/librarys/skeleton-api.js
  src/librarys/video-api.js
  src/pages/CourseDetail.jsx
  src/pages/PlayerPage.jsx
  src/reducer/player.js
  src/redux/modalSlice.js
Labels: 🔨 feature, 💻 frontend

#43 [Feat/FE] 라우팅 리팩토링 및 비로그인시 로그인 modal 표시 기능 추가한다.
  src/App.jsx
  src/components/ProtectedRoute.jsx
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend

#44 [Feat/FE] API를 연결한다. (1차)
  src/App.jsx
  src/App.scss
  src/components/Header.jsx
  src/components/SkeletonVideo.jsx
  src/librarys/admin-api.js
  src/librarys/axios.js
  src/librarys/player.js
  src/librarys/skeleton-api.js
  src/librarys/util.js
  src/librarys/video-api.js
  src/main.jsx
  src/pages/AddExercise.jsx
  src/pages/CourseDetail.jsx
  src/pages/PlayerPage.jsx
  src/reducer/player.js
Labels: 🔨 feature, 🔧 fix_issue, 💻 frontend

#47 [Refator/FE]: 공개 SW 개발자대회 본선을 위한 코드 재정비
  package-lock.json
  src/App.jsx
  src/components/CourseCard.jsx
  src/components/LoginModal.jsx
  src/pages/AddExercise.jsx
  src/pages/CourseDetail.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/MyCourse.jsx
  src/pages/SignUpPage.jsx
Labels: 💻 frontend, 🛠️ refactoring
