Repository MotuS-Web/MotuS-FrontEnd, pull requests merged in 2023-10, with the labels that each got.

#50 [Feat/FE] Motus 최종버전 002 003 세부 운동 정보 모달, 운동 등록하기 페이지를 구현한다.
  src/App.jsx
  src/App.scss
  src/assets/icons/Page-left.png
  src/components/AddHeader.jsx
  src/components/BackButton.jsx
  src/components/ExerciseCard.jsx
  src/components/ExerciseList.jsx
  src/components/ExerciseModal.jsx
  src/components/VideoUploader.jsx
  src/pages/AddExercise.jsx
Labels: 🔨 feature, 💻 frontend, 📱 ui

#51 [Refactor/FE] 메인 페이지의 코드를 정리하고 디자인을 수정한다.
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/components/ExerciseCard.jsx
  src/components/ExerciseList.jsx
  src/components/ExerciseModal.jsx
  src/components/FilterButtons.jsx
  src/components/Header.jsx
  src/components/ProtectedRoute.jsx
  src/components/SearchBar.jsx
  src/components/Tag.jsx
  src/components/Thumbnail.jsx
  src/components/UploadButton.jsx
  src/index.scss
  src/pages/MainPage.jsx
Labels: 💻 frontend, 🛠️ refactoring, 📱 ui

#52 [Feat/FE] 메인 페이지에 애니메이션을 추가하고 페이지 이동 기능을 추가한다.
  src/components/ExerciseCard.jsx
  src/components/ExerciseList.jsx
  src/components/ExerciseModal.jsx
  src/components/Header.jsx
  src/components/UploadButton.jsx
  src/librarys/player.js
  src/pages/AddExercise.jsx
  src/pages/MainPage.jsx
Labels: 💻 frontend, 📱 ui, 🎨 design

#53 Refactor: 영상 게시 페이지 코드 정리 및 디자인 정리
  src/components/AddHeader.jsx
  src/components/BackButton.jsx
  src/components/FilterButtons.jsx
  src/components/Header.jsx
  src/pages/AddExercise.jsx
Labels: 💻 frontend, 📱 ui, 🎨 design

#56 [Feat/FE] 동영상 업로드 페이지의 API를 새로운 버전으로 연결한다.
  src/components/SkeletonVideo.jsx
  src/components/TagSelect.jsx
  src/components/VideoUploader.jsx
  src/components/player/BorderBox.jsx
  src/components/player/ControllerSection.jsx
  src/components/player/Countdown.jsx
  src/components/player/GuideSection.jsx
  src/librarys/axios.js
  src/librarys/context.js
  src/librarys/player.js
  src/librarys/type.js
  src/pages/AddExercise.jsx
  src/reducer/upload.js
Labels: 💻 frontend, 🛠️ refactoring

#57 [Feat/FE] 메인페이지와 운동 카드 컴포넌트 비디오 목록 조회 API연결을 진행한다.
  src/components/ExerciseCard.jsx
  src/components/ExerciseModal.jsx
  src/components/FilterButtons.jsx
  src/components/Tag.jsx
  src/components/Thumbnail.jsx
  src/librarys/exercise-api.js
  src/librarys/type.js
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend

#58 Feat: 검색 기능 구현
  src/components/Header.jsx
  src/components/SearchBar.jsx
  src/librarys/exercise-api.js
  src/pages/MainPage.jsx
Labels: 🔨 feature, 💻 frontend

#59 Refactor: 프로젝트 코드를 정리한다.
  .env
  README.md
  index.html
  public/android-icon-144x144.png
  public/android-icon-192x192.png
  public/android-icon-36x36.png
  public/android-icon-48x48.png
  public/android-icon-72x72.png
  public/android-icon-96x96.png
  public/apple-icon-114x114.png
  public/apple-icon-120x120.png
  public/apple-icon-144x144.png
  public/apple-icon-152x152.png
  public/apple-icon-180x180.png
  public/apple-icon-57x57.png
  public/apple-icon-60x60.png
  public/apple-icon-72x72.png
  public/apple-icon-76x76.png
  public/apple-icon-precomposed.png
  public/apple-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon-96x96.png
  public/favicon.ico
  public/manifest.json
  public/ms-icon-144x144.png
  public/ms-icon-150x150.png
  public/ms-icon-310x310.png
  public/ms-icon-70x70.png
  public/vite.svg
  src/App.jsx
  src/assets/icons/LOGO.png
  src/assets/icons/icon.png
  src/components/AddHeader.jsx
  src/components/ExerciseCard.jsx
  src/components/FilterButtons.jsx
  src/components/Header.jsx
  src/components/Thumbnail.jsx
  src/librarys/admin-api.js
  src/librarys/axios.js
  src/librarys/context.jsx
  src/pages/AddExercise.jsx
  src/pages/PlayerPage.jsx
  vite.config.js
Labels: 💻 frontend, ⚙️ infra, 🛠️ refactoring

#60 Docs: 표 깨짐 수정
  README.md
Labels: 📰 documentation, 💻 frontend

#61 Docs: 리드미 수정
  README.md
Labels: 📰 documentation

#62 Refactor: 프론트엔드 코드 리팩토링을 진행한다.
  src/components/AddHeader.jsx
  src/components/Tag.jsx
  src/components/TagSelect.jsx
  src/components/button/BackButton.jsx
  src/components/button/FilterButtons.jsx
  src/components/button/UploadButton.jsx
  src/components/exercise/ExerciseCard.jsx
  src/components/exercise/ExerciseModal.jsx
  src/components/exercise/Tag.jsx
  src/components/exercise/Thumbnail.jsx
  src/components/exercise/VideoUploader.jsx
  src/components/header/Header.jsx
  src/components/header/SearchBar.jsx
  src/librarys/admin-api.js
  src/librarys/login-api.js
  src/pages/AddExercise.jsx
  src/pages/MainPage.jsx
Labels: 💻 frontend, 🛠️ refactoring

#64 Feat: 테스트 코드 제거 및 디자인 다듬기
  src/components/header/Header.jsx
  src/components/player/GuideSection.jsx
  src/librarys/axios.js
  src/librarys/player.js
  src/pages/AddExercise.jsx
  src/pages/PlayerPage.jsx
Labels: 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#65 [BUG/FIX/FE] 필터링 해제 실패 이슈와 페이지네이션 기능 구현하였습니다.
  package-lock.json
  package.json
  src/App.scss
  src/assets/icons/Page-right.png
  src/components/button/FilterButtons.jsx
  src/components/exercise/ExerciseCard.jsx
  src/components/exercise/ExerciseModal.jsx
  src/components/exercise/Tag.jsx
  src/components/exercise/TagSelect.jsx
  src/components/pagnation/Pagination.jsx
  src/librarys/exercise-api.js
  src/pages/AddExercise.jsx
  src/pages/MainPage.jsx
Labels: 🔨 feature, 🔧 fix_issue, 🔥 hotfix, 🛠️ refactoring, 📱 ui

#66 [Refactor/FE] 메인 페이지의 modal을 VideoModal로 수정, BorderBox 코드 개선
  .env
  README.md
  package-lock.json
  src/components/Modal.jsx
  src/components/VideoModal.jsx
  src/components/exercise/ExerciseModal.jsx
  src/components/player/BorderBox.jsx
  src/librarys/type.js
  src/pages/MainPage.jsx
Labels: 🔧 fix_issue, 💻 frontend, 🛠️ refactoring

#68 Docs: 리드미에 Banner 이미지 추가
  README.md
Labels: 📰 documentation

#69 Docs: CONTRIBUTING.md 추가
  CONTRIBUTING.md
  README.md
Labels: 📰 documentation
